import Head from "next/head";
import { Navbar } from "../components/Home";
import Content from "../components/Home/Content/Content";

export default function home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />
      <Content />
      {/* footer */}
    </>
  );
}
